sudo: false
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script:
  - sbt -Dconfig.file="modules/api/src/main/resources/application.conf" ++$TRAVIS_SCALA_VERSION "project tests" clean coverage test
after_success:
  - sbt -Dconfig.file="modules/api/src/main/resources/application.conf" ++$TRAVIS_SCALA_VERSION "project tests" coverageReport
  - sbt -Dconfig.file="modules/api/src/main/resources/application.conf" ++$TRAVIS_SCALA_VERSION "project tests" coverageAggregate
  - sbt -Dconfig.file="modules/api/src/main/resources/application.conf" ++$TRAVIS_SCALA_VERSION "project tests" codacyCoverage
