sudo: false
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
services:
  - redis-server
  - postgresql
before_script:
  - psql -c 'create database ninecards_travis_ci_test;' -U postgres
script:
  - sbt -Dconfig.file="modules/api/src/test/resources/test.conf" ++$TRAVIS_SCALA_VERSION "project tests" clean coverage test
after_success:
  - sbt -Dconfig.file="modules/api/src/test/resources/test.conf" ++$TRAVIS_SCALA_VERSION "project tests" coverageReport
  - sbt -Dconfig.file="modules/api/src/test/resources/test.conf" ++$TRAVIS_SCALA_VERSION "project tests" coverageAggregate
  - sbt -Dconfig.file="modules/api/src/test/resources/test.conf" ++$TRAVIS_SCALA_VERSION "project tests" codacyCoverage
after_script:
  - psql -c 'drop database ninecards_travis_ci_test;' -U postgres
addons:
  apt:
    packages:
      - protobuf-compiler
