sudo: false
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
services:
  - redis-server
script:
  - sbt ++$$TRAVIS_SCALA_VERSION clean coverage
  - sbt -Dconfig.file="src/test/resources/test.conf" test
addons:
  apt:
    packages:
      - protobuf-compiler
