sudo: false
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION "project tests" clean coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION "project tests" coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION "project tests" coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION "project tests" codacyCoverage
